### PR TITLE
building some SCP-firmware resources without notification/multithread/...

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Review by jimqui01 — CHANGES_REQUESTED** [review]
DVFS can handle asynchronous requests in single-threaded mode

**Comment by jimqui01** [comment]
jenkins: ok to test

**Review by nicola-mazzucato-arm — COMMENTED** [review]
PD is already capable of handling single thread execution. or am I missing something?

**Comment by etienne-lms** [comment]
deprecated

**Pull request closed without merging**
