### PR TITLE
Fix inconsistencies with BUILD_HAS_xxx

### PR DESCRIPTION
**Pull request by etienne-lms**
Few occurence of `#if BUILD_HAS_xxx` are replaced with `#ifdef BUILD_HAS_xxx`.

### CODE REVIEW

**Review by nicola-mazzucato-arm — CHANGES_REQUESTED** [review]
there's a typo in this commit message s/BUIDL/BUILD

**Comment by etienne-lms** [comment]
Issue in commit log fixed.

**Comment by nicola-mazzucato-arm** [comment]
Jenkins: ok to test

**Comment by nicola-mazzucato-arm** [comment]
Jenkins: ok to test

**Comment by nicola-mazzucato-arm** [comment]
@etienne-lms can you please update copyright year and re-push? Many thanks

**Comment by etienne-lms** [comment]
Ok, done. I've rebased the series.

**Review by nicola-mazzucato-arm — APPROVED** [review]

**Pull request merged**
