### PR TITLE
Multiple cases of  explicit type casting unsigned int(uint32_t) to int

### LINKED ISSUE #783: Multiple cases of explicit type casting from unsigned int (uint32_t) to int
[module/resource_perms/src/mod_resource_perms.c](https://github.com/ARM-software/SCP-firmware/blob/master/module/resource_perms/src/mod_resource_perms.c#L350)
Variable message_offset and resource_size at line no. 350,349 
`resource_size = (int)resources_perms_ctx.clock_count;`

### PR DESCRIPTION
**Pull request by Sanchit-kumar**
Fixes #783

### CODE REVIEW

**Review by leandro-arm — CHANGES_REQUESTED** [review]
Hi @Sanchit-kumar, could you please sign off your patch and explain the reason of this change?
Thanks

**Comment by Sanchit-kumar** [comment]
Signed off patch with explanation along with the code style violation change commit.

**Review by nicola-mazzucato-arm — CHANGES_REQUESTED** [review]
I am not sure to understand. This change looks like a code-style update to me, rather than a type casting.
Can you please clarify better where the issue is?
Thanks

**Comment by nicola-mazzucato-arm** [comment]
@Sanchit-kumar sorry for the late reply.
Can you please tidy up the patches. In particular, there's a merge branch commit which will need to be removed, before potentially merge the PR.
Thanks

**Pull request closed without merging**
