### PR TITLE
SCMI Notifications for Performance Protocol

### PR DESCRIPTION
**Pull request by jimqui01**

### CODE REVIEW

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
Jenkins, test this please.

**Comment by jimqui01** [comment]
Jenkins, test this please.

**Comment by jimqui01** [comment]
Jenkins, test this please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by jimqui01** [comment]
Jenkins, test this please.

**Comment by jimqui01** [comment]
Jenkins, test this please.

**Pull request merged**
