### PR TITLE
product/optee-fvp: fix gpu perf level

### PR DESCRIPTION
**Pull request by vingu-linaro**
Fix a wong gpu perf level.
scmi compliance test reported error.

Signed-off-by: Vincent Guittot <vincent.guittot@linaro.org>

### CODE REVIEW

**Review by nicola-mazzucato-arm — APPROVED** [review]

**Comment by nicola-mazzucato-arm** [comment]
Jenkins: ok to test

**Comment by nicola-mazzucato-arm** [comment]
@vingu-linaro Copyright needs to be updated for the tests to pass :)

**Review by leandro-arm — CHANGES_REQUESTED** [review]
Modified files should have in the copyright header the right date, in this case `2022-2023`

**Comment by vingu-linaro** [comment]
Hi @nicola-mazzucato-arm and @leandro-arm ,

Ok, will update the copyright header

**Pull request merged**
