### PR TITLE
Experimental: products: Disable multi-threading for all products

### PR DESCRIPTION
**Pull request by girishpathak**
This change is a precursor to the subsequent changes where
multi-threading support will be removed from the SCP firmware.

The change is inteded to allow platform owners to test respective
platforms without multi-threading.

The term multi-threaded mode is misleading since it implies multiple
threads of execution are concurrently supported
(like in an OS), but that is not true. Also multi-threading add call
overhead and could make things slower, and creates a larger memory
footprint. Simply all of above is not needed at present, hence we
expect multi-thread mode to be removed in near future from the firmware.

Change-Id: Ia5009ddf75a5f385ee8a8966e178900e462e6cf9
Signed-off-by: Girish Pathak <girish.pathak@arm.com>

### CODE REVIEW

**Comment by girishpathak** [comment]
@masahisak: We are planning to remove multi-threading support from SCP Firmware. The reason for this is mentioned in the commit/PR message.  We observed that fwk_thread_create is used by mod_syqnacer_system, Can you please try this PR? You probably need to re-work mod_syqnacer_system to make it work.

**Comment by girishpathak** [comment]
@n-royer : Can you also please try this PR and let us know your feedback ?

**Comment by masahisak** [comment]
> @masahisak : We are planning to remove multi-threading support from SCP Firmware. The reason for this is mentioned in the commit/PR message. We observed that fwk_thread_create is used by mod_syqnacer_system, Can you please try this PR? You probably need to re-work mod_syqnacer_system to make it work.

@girishpathak 
Eventually, fwk_thread_create() is not needed even if multi-threading is enabled, we can safely remove this thread creation.
Apart from removing thread creation, we need to remove osDelay() call on SynQuacer platform support.
Anyway, we can live without multi-threading.

**Comment by girishpathak** [comment]
> > @masahisak : We are planning to remove multi-threading support from SCP Firmware. The reason for this is mentioned in the commit/PR message. We observed that fwk_thread_create is used by mod_syqnacer_system, Can you please try this PR? You probably need to re-work mod_syqnacer_system to make it work.
> 
> @girishpathak
> Eventually, fwk_thread_create() is not needed even if multi-threading is enabled, we can safely remove this thread creation.
> Apart from removing thread creation, we need to remove osDelay() call on SynQuacer platform support.
> Anyway, we can live without multi-threading.

Thank you for you reply

**Comment by girishpathak** [comment]
> @n-royer : Can you also please try this PR and let us know your feedback ?

@n-royer: Any feedback?

**Comment by n-royer** [comment]
> > @n-royer : Can you also please try this PR and let us know your feedback ?
> 
> @n-royer: Any feedback?

I'll check tomorrow

**Comment by n-royer** [comment]
@girishpathak : Something has been broken before this PR. So I can't test it but it looks good for us.

**Comment by girishpathak** [comment]
> @girishpathak : Something has been broken on RCAR before this PR. So I can't test it but it looks good for us.

Thank you for your reply

**Comment by girishpathak** [comment]
@vingu-linaro: Can you also have a look in this PR and let us know your feedback too.

**Comment by vingu-linaro** [comment]
@girishpathak 
Multithreading is enabled when I use scp-firmware with zephyr to reuse the cmsis interface. In such case the requests are processed in thread context. When  i disable the multithreading, this still works but the request and the scmi statemachine is processed in the interrupt context.

**Comment by girishpathak** [comment]
> @girishpathak
> Multithreading is enabled when I use scp-firmware with zephyr to reuse the cmsis interface. In such case the requests are processed in thread context. When i disable the multithreading, this still works but the request and the scmi statemachine is processed in the interrupt context.

@vingu-linaro: Yes, this is expected, Do you have any concerns with that? If not, the plan is to remove the multi-threading altogether.

**Comment by vingu-linaro** [comment]
@girishpathak  I wonder if this can be a problem if scp-firmware wants to use a zephyr driver in one of this module

**Comment by masahisak** [comment]
@girishpathak  We are working for disabling multi-threading option from SynQuacer platform. I encounter the following compile warning regarding the use of fwk_thread_put_event_and_wait() API in the power_domain module.

```
SCP-firmware/module/power_domain/src/mod_power_domain.c:1509:5: warning: 'fwk_thread_put_event_and_wait' is deprecated [-Wdeprecated-declarations]
 1509 |     status = fwk_thread_put_event_and_wait(&req, &resp);
```
May we know the plan about fwk_thread_put_event_and_wait()? Can we safely disable multi-threading option now?

**Comment by tarek-arm** [comment]
@masahisak The warning is expected. Currently, we are working on removing this function 'fwk_thread_put_event_and_wait' from the power domain module. We planned this in stages, the function will be removed then multi-threading.
You can safely switch to mono-threading now and the warning will disappear in due course.

**Comment by masahisak** [comment]
> @masahisak The warning is expected. Currently, we are working on removing this function 'fwk_thread_put_event_and_wait' from the power domain module. We planned this in stages, the function will be removed then multi-threading. You can safely switch to mono-threading now and the warning will disappear in due course.

@girishpathak 
Thank you. I have send PR #541 to disable multi-threading from SynQuacer.

**Comment by girishpathak** [comment]
> > @masahisak The warning is expected. Currently, we are working on removing this function 'fwk_thread_put_event_and_wait' from the power domain module. We planned this in stages, the function will be removed then multi-threading. You can safely switch to mono-threading now and the warning will disappear in due course.
> 
> @girishpathak Thank you. I have sent PR #541 to disable multi-threading from SynQuacer.

@masahisak Thank you for this, we will check the PR.

**Comment by masahisak** [comment]
@girishpathak 
If we disable multi-threading option, SCP-firmware does busy loop even if SCP-firmware is in idle state.
Is there any plan to let SCP-firmware sleep in idle state something like following?
```
diff --git a/framework/src/fwk_thread.c b/framework/src/fwk_thread.c
index 1a97051a..24f9e979 100644
--- a/framework/src/fwk_thread.c
+++ b/framework/src/fwk_thread.c
@@ -317,6 +318,7 @@ noreturn void __fwk_thread_run(void)
         }

         (void)fwk_log_unbuffer();
+        __WFI();
     }
```
If there are some reason not to enter sleep state in SCP-firmware idle loop, it is very helpful for us to know the details.

**Comment by nicola-mazzucato-arm** [comment]
Hi @girishpathak , can we close this PR? Thank you.

**Comment by girishpathak** [comment]
Deleting experimental pull request.

**Pull request closed without merging**
