### PR TITLE
Replace signals with Light events and minor runtime performance optimizations

### PR DESCRIPTION
**Pull request by girishpathak**
This pull request contains the changes which may improve the runtime performance of some use cases such as SCMI requests.

This change replaces signals with light events and adds other minor improvements.

### CODE REVIEW

**Comment by girishpathak** [comment]
@masahisak: We are planning to merge this PR next week,  Have a look at this PR, if any concerns, please reply

**Comment by masahisak** [comment]
> @masahisak: We are planning to merge this PR next week, Have a look at this PR, if any concerns, please reply

There is no concern regarding this PR. Thank you for sharing this change.

**Comment by girishpathak** [comment]
jenkins: ok to test

**Comment by girishpathak** [comment]
jenkins: ok to test

**Comment by girishpathak** [comment]
jenkins: ok to test

**Review by tarek-arm — APPROVED** [review]

**Comment by girishpathak** [comment]
Jenkins: ok to test

**Comment by girishpathak** [comment]
jenkins: ok to test

**Pull request merged**
