### PR TITLE
Ag/disable resource permission by default

### PR DESCRIPTION
**Pull request by AhmedImbabyGadallah**
This change allows to disable resource permissions with no errors and also disables resource permissions for juno platform.

### CODE REVIEW

**Review by jimqui01 — APPROVED** [review]
jenkins: ok to test

**Review by girishpathak — CHANGES_REQUESTED** [review]
what is bs/Juno ?  use product/juno

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by AhmedImbabyGadallah** [comment]
bs stands for build system as I have changed firmware.mk file

**Comment by tarek-arm** [comment]
Testing OK

**Pull request merged**
