### PR TITLE
Platform/Product port for rcar

### PR DESCRIPTION
**Pull request by n-royer**

### CODE REVIEW

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
Note: I added a commit to this PR to avoid trying to build the .srec files for the platforms when building with armclang.

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
The checks are failing for 

Check copyright: Failed
Check spacing: Failed
Check tabs: Failed
Check doc: Failed

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by nicola-mazzucato-arm** [comment]
@n-royer The rcar platform has been merged. Can we please close this PR? Thank you

**Comment by n-royer** [comment]
Merged from another PR.

**Comment by n-royer** [comment]
Done

**Pull request closed without merging**
