### PR TITLE
Add disabled PSCI protocols when resource permission feature is disabled

### PR DESCRIPTION
**Pull request by AhmedImbabyGadallah**
Add disabled protocols configurations for sgm775,sgm776,sgi575,rdn1e1
and tc0 platforms when resource permissions option is disabled.

### CODE REVIEW

**Review by nicola-mazzucato-arm — CHANGES_REQUESTED** [review]
Please split the change across each of the platforms. That would ease cherry-picking. Thanks

**Comment by tarek-arm** [comment]
jenkins: OK to test

**Comment by AhmedImbabyGadallah** [comment]
Close this PR and open another one with the 5 required commits

**Comment by AhmedImbabyGadallah** [comment]
The requested Change is done

**Review by nicola-mazzucato-arm — APPROVED** [review]

**Pull request merged**
