### PR TITLE
Experimental: Merge PR #670 (Transport Module)

### PR DESCRIPTION
**Pull request by girishpathak**
This PR is raised to merge PR #670. We need this experimental PR because of the recent change to CI nodes that updated the lcov tool which seems to be incompatible with other tools. 

Apart from commits in PR #670. This PR includes commit [Makefile.cmake: Disable code coverage](https://github.com/ARM-software/SCP-firmware/pull/671/commits/6ff1eb59f194abc407d4acdd52d5b51041c043ad) which temporarily disables this feature.  Since code coverage tool is still in development phase and it executes only on sample unit test cases, we can safely disable this tool to progress merging of PR #670.

### CODE REVIEW

**Comment by girishpathak** [comment]
Jenkis: ok to test

**Comment by girishpathak** [comment]
Jenkins:ok to test

**Comment by girishpathak** [comment]
Jenkins: ok to test

**Comment by girishpathak** [comment]
jenkins:ok to test

**Comment by girishpathak** [comment]
jenkins: ok to test

**Comment by girishpathak** [comment]
Jenkins: ok to test

**Comment by girishpathak** [comment]
Jenkins: ok to test

**Comment by nicola-mazzucato-arm** [comment]
@girishpathak Please abandon this PR since PR670 has been merged successfully. Thanks!

**Comment by girishpathak** [comment]
As experimental PR, merge is not required

**Pull request closed without merging**
