### PR TITLE
Add I/O framework

### PR DESCRIPTION
**Pull request by CJKay**
This pull requests adds the input/output framework, which integrates a byte-stream I/O API into the framework. In addition, both the logging and CLI components have been ported to utilize these new APIs.

### CODE REVIEW

**Review by jimqui01 — APPROVED** [review]

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by jimqui01** [comment]
jenkins: ok to test

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Pull request merged**
