### PR TITLE
Add compiler-specific macro facades

### PR DESCRIPTION
**Pull request by CJKay**
This pull requests adds a number of macros that act as facades for certain compiler extensions.

### CODE REVIEW

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Comment by CJKay** [comment]
Jenkins: test this, please.

**Review by nicola-mazzucato-arm — APPROVED** [review]

**Pull request merged**
