### PR TITLE
cli: changed reset command to weak symbol to allow override

### PR DESCRIPTION
**Pull request by yaronm-hailo**
This allows us to have a working reset command in the debugger CLI by creating our own reset_sys_f function

### CODE REVIEW

**Comment by tarek-arm** [comment]
Jenkins: OK to test

**Review by leandro-arm — CHANGES_REQUESTED** [review]
Can you please edit line 3 to update the date to `2020-2023`?

**Comment by yaronm-hailo** [comment]
@leandro-arm done

**Comment by leandro-arm** [comment]
Jenkins: ok to test

**Review by leandro-arm — APPROVED** [review]

**Pull request merged**
