### PR TITLE
Topics/cpu info

### PR DESCRIPTION
**Pull request by nissha03**
Request for pulling changes for cpu_info

### CODE REVIEW

**Comment by tarek-arm** [comment]
Jenkins: OK to test

**Comment by nicola-mazzucato-arm** [comment]
@nissha03 you may need to rebase on latest and re-push the PR for the CI to pass, thanks.

**Comment by nissha03** [comment]
> @nissha03 you may need to rebase on latest and re-push the PR for the CI to pass, thanks.
Hi Nicola, it is already on the top of tree. The build is failing due to some unrelated issue.
Do I need to push it again to restart the build?

**Comment by nicola-mazzucato-arm** [comment]
@nissha03 please add a better description of this PR before I merge it. Thanks

**Review by tarek-arm — APPROVED** [review]

**Pull request merged**
