### PR TITLE
Ci static analysis

### PR DESCRIPTION
**Pull request by DakeyR**
This PR fixes mistakes discovered by Cppcheck static analyzer and introduces a files for performing static analysis in the Continuous Integration process.

### CODE REVIEW

**Comment by DakeyR** [comment]
@manojkumar-arm Can you approve the N1SDP related changes please ?

**Comment by nicola-mazzucato-arm** [comment]
Jenkins: ok to test

**Comment by CJKay** [comment]
> @manojkumar-arm Can you approve the N1SDP related changes please ?

Approved internally, ready to merge.

**Comment by manojkumar-arm** [comment]
Approved changes for N1SDP.

**Pull request merged**
