### PR TITLE
CMake build support for rcar

### PR DESCRIPTION
**Pull request by girishpathak**
This PR is a part of the ongoing CMake patch series.  The current build system will be replaced with CMake in near future.

This PR includes commits with the modification that will support the building of rcar platform using CMake.

Please review and test

### CODE REVIEW

**Comment by girishpathak** [comment]
@n-royer : Can you please test and review this change?

**Comment by n-royer** [comment]
It doesn't build on my environment:
================================================================
Arm SCP/MCP Software build System
Platform    : rcar
Mode        : debug
Firmware(s) : scp_ramfw
================================================================
CMake Error: The source directory "/home/nroyer/projects/scp/cmake/SCP-firmware/--log-level=NOTICE" does not exist.

**Comment by girishpathak** [comment]
> 
> 
> It doesn't build on my environment:
> 
> Arm SCP/MCP Software build System
> Platform : rcar
> Mode : debug
> Firmware(s) : scp_ramfw
> CMake Error: The source directory "/home/nroyer/projects/scp/cmake/SCP-firmware/--log-level=NOTICE" does not exist.

Thanks for trying this out. I'm just wondering if you have following the instructions in 
doc/cmake_readme.md.

https://github.com/ARM-software/SCP-firmware/blob/master/doc/cmake_readme.md

Can you also let us know, steps you followed to get the PR. did you checkout  girishpathak:cmake_rcar_v1 ? or did you cherry-pick commits ?

**Comment by girishpathak** [comment]
@n-royer : Can you please provide your update on this?

**Comment by n-royer** [comment]
> @n-royer : Can you please provide your update on this?

Yes, I'll do it today

**Review by n-royer — APPROVED** [review]

**Review by nicola-mazzucato-arm — APPROVED** [review]

**Comment by nicola-mazzucato-arm** [comment]
Jenkins: ok to test

**Pull request merged**
